### ISSUE TITLE
Some icons not updated

### ISSUE THREAD

**Issue by cervonwong** [bennymeg/ngx-fluent-ui#1]
Some icons, for example `Document Heart` and `Equal Off` cannot be found in the web client.

**Comment by bennymeg** [comment]
The icon database updates automaticlly weekly. If the icons you mentioned are new, check again next week, if not, try clearing your browser cache.

**Comment by cervonwong** [comment]
Hi, I checked and some of the icons like the `Document Heart` and `Equal Off` that were added a few weeks back are still not on the site.

**Comment by bennymeg** [comment]
I have updated the icons manually, You can use find all the new icons now.
Please let me know next time there is a new icon so I can check if the pipeline is working correctly. (I Believe everything works fine)

**Comment by cervonwong** [comment]
Most of the icons from this PR https://github.com/microsoft/fluentui-system-icons/pull/257 is still not updated. 😅 Thanks for taking your time to look into this! :)

**Comment by bennymeg** [comment]
You were right! 

It seems that angular bundled some of the icons definitions. Since the the weekly update action only updated the definitions file and not built the site, it was not updated. 
It seems to work fine now (just clear your cache if it doesn't).

I'll update the action late this week, thank for letting me know about this issue!
